version: '3.3'
services:
  server:
    build: .
    volumes:
      - './:/app'
    ports:
      - '8081:8081'
    depends_on:
      - 'mongo'
    environment:
      MONGODB_URL: 'mongodb://mongo:27017'
    networks:
      - crud
  mongo:
    image: 'mongo:latest'
    ports:
      - '27017:27017'
    networks:
      - crud

networks:
  crud:
    driver: bridge